# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache2-AuthZSympa
version:      0.4.0
version_from: lib/Apache2/AuthZSympa.pm
installdirs:  site
requires:
    Apache2::Access:               0
    Apache2::Log:                  0
    Apache2::RequestRec:           0
    Apache2::RequestUtil:          0
    Apache2::Response:             0
    Apache2::SubRequest:           0
    Cache::Memcached:              0
    mod_perl2:                     0
    Net::LDAP:                     0
    SOAP::Lite:                    0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
